### ISSUE TITLE
Keine Texte und Nutzungsschablone

### ISSUE THREAD

**Issue by JeltoBuurman** [bstroebl/xplanplugin#12]
Hallo,

ich versuche einen Testdatensatz einzulesen:
[BPlan001_5-2.zip](https://github.com/bstroebl/xplanplugin/files/7685736/BPlan001_5-2.zip)
Nachdem beim ersten Versuch der zweite Schritt des Import fehlgeschlagen war, habe ich die Layermit den "emmisionen"  gelöscht und danach konnte ich den BPLan anfassen, aber leider ohne Texte und Nutzungschablone. 

Gibt es einen Hinweis?

Danke 

Jelto Buurman

PS. Die Tabellen "XP_PPO" und XP_PTO" haben keine Attribute

**Comment by bstroebl** [comment]
Hallo Jelto,
woher stammt der Testdatensatz? Hintergrund: Ich weiß, dass es beim Einlesen der Testdatensätze der XPlanleitstelle Probleme gibt, konnte mich aber noch nicht damit beschäftigen.
Was heißt "ohne Texte und Nutzungsschablone"? Fehlen die Einträge in den Tabellen oder sind sie zwar da, aber Du siehst sie in der Karte nicht?
Was bedeutet "XP_PPO" und XP_PTO" haben keine Attribute? Bei einer standardmässigen Anlage der DB haben sie Attribute. Oder haben die Datensätze aus dem Import keine Attributwerte?
Sorry für die vielen Fragen
Grüße
Bernhard

**Comment by JeltoBuurman** [comment]
Hallo Bernhard,

vielen Dank für Deine schnelle Antwort.
1. Der Datensatz stammt von:
https://bitbucket.org/geowerkstatt-hamburg/xplan-testdaten/src/master/
2. Ich vermute, dass Texte und Nutzungsschablonen aus den Tabellen
xp_ppo und xp_pto erzeugt werden, die sind als Punkte vorhanden sind jedoch
ohne Attribute.
3. Die Tabellen im Importbereich haben, soweit sich mir das erschließt,
Attribute.

Ich habe noch einen Dump meiner Datenbank 11.6 beigelegt (xplanung|xplan)

Vielen Dank
Gruuß

Jelto

Am Do., 9. Dez. 2021 um 16:00 Uhr schrieb Bernhard Ströbl <
***@***.***>:

**Comment by bstroebl** [comment]
Für Nutzungsschablonen gibt es eine eigene Objektart XP_Praesentationsobjekte.XP_Nutzungsschablone, abgleitet von XP_PTO. Hast Du XP_Nutzungsschablone reingeladen?

**Comment by JeltoBuurman** [comment]
Hallo, xp_nutzungsschablone ist angelegt, aber leer. Wie bekomme ich dort Daten hinein?GrußJeltoVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Bernhard Ströbl ***@***.***> Datum: 09.12.21  16:41  (GMT+01:00) An: bstroebl/xplanplugin ***@***.***> Cc: JeltoBuurman ***@***.***>, Author ***@***.***> Betreff: Re: [bstroebl/xplanplugin] Keine Texte und Nutzungsschablone (Issue #12) 

Für Nutzungsschablonen gibt es eine eigene Objektart XP_Praesentationsobjekte.XP_Nutzungsschablone, abgleitet von XP_PTO. Hast Du XP_Nutzungsschablone reingeladen?

**Comment by bstroebl** [comment]
> Wie bekomme ich dort Daten hinein?

Indem Du wlche digitalisierst :-)
Da Du welche importierst, kann ich das erst beantworten, wenn ich mich mit dem Import Deines Beispieldatensatzes beschäftigt habe.

**Comment by bstroebl** [comment]
Hallo Jelto,
ich habe den Beispielsdatensatz in eine frische Datenbank importiert. Dabei ist mir folgendes aufgefallen:
1) der Import von Präsentationsobjekten ist z.Zt. schlecht; ich hatte bisher schlicht keine Beispiele. Wird nachgebessert, dann sollte zumindest der Schriftinhalt der PTO-Objekte mitkommen, ausserdem die "dientZurDarstellungVon"-Geschichte.
2) die Modellierung der "Nutzungsschablonen" über PPO ist IMHO nicht sinnvoll. Ein PPO wird durch ein Symbol dargestellt, hier soll aber Text dargestellt werden. Warum wird nicht PTO benutzt oder, weil es sich ja um eine Nutzungsschablone handelt, die dafür vorgesehene Klasse XP_Nutzungsschablone? Um hier mit PPO zu einer Darstellung wie in Deinem png zu kommen, müsste jedem PPO-Feature in Abhängigkeit von seinem Wert in _Art_ ein textliches Symbol zugewiesen werden. Das geht nicht automatisch und erscheint reichlich umständlich, wo es doch _XP_PTO_ bzw. _XP_Nutzungsschablone_ gibt.

**Comment by JeltoBuurman** [comment]
Hallo Bernhard, Vielen Dank für deine Mühe. Ich habe inzwischen noch einmal versucht die Objekte mit der data-driven inputmask zu bearbeiten. Leider ließ sich die Maske nicht öffnen. (Value out of range) die zusätzlichen Tabellen um die Daten einzugeben wurden aber ins Projekt eingebunden. Vielleicht fällt dir ja auch dazu noch etwas ein.Ansonsten wünsche ich dir ein frohes Fest und einen guten Rutsch ins neue Jahr falls wir uns nicht mehr hören.Gruß JeltoVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Bernhard Ströbl ***@***.***> Datum: 16.12.21  08:38  (GMT+01:00) An: bstroebl/xplanplugin ***@***.***> Cc: JeltoBuurman ***@***.***>, Author ***@***.***> Betreff: Re: [bstroebl/xplanplugin] Keine Texte und Nutzungsschablone (Issue #12) 

Hallo Jelto,

ich habe den Beispielsdatensatz in eine frische Datenbank importiert. Dabei ist mir folgendes aufgefallen:



der Import von Präsentationsobjekten ist z.Zt. schlecht; ich hatte bisher schlicht keine Beispiele. Wird nachgebessert, dann sollte zumindest der Schriftinhalt der PTO-Objekte mitkommen, ausserdem die "dientZurDarstellungVon"-Geschichte.

die Modellierung der "Nutzungsschablonen" über PPO ist IMHO nicht sinnvoll. Ein PPO wird durch ein Symbol dargestellt, hier soll aber Text dargestellt werden. Warum wird nicht PTO benutzt oder, weil es sich ja um eine Nutzungsschablone handelt, die dafür vorgesehene Klasse XP_Nutzungsschablone? Um hier mit PPO zu einer Darstellung wie in Deinem png zu kommen, müsste jedem PPO-Feature in Abhängigkeit von seinem Wert in Art ein textliches Symbol zugewiesen werden. Das geht nicht automatisch und erscheint reichlich umständlich, wo es doch XP_PTO bzw. XP_Nutzungsschablone gibt.

**Comment by bstroebl** [comment]
XPlanung nutz auch die _DataDrivenInputMask_, d.h. genau das selbe müsste dort auch nicht gehen. Mir wurde der _Value out of range_ - Fehler bereits berichtet. Ich konnte ihn hier nicht reproduzieren. Welchen LAyer versuchst Du mit der DDIM zu bearbeiten? Auf welchem Betriebssystem läuft Deine DB?

**Comment by JeltoBuurman** [comment]
Hallo Bernhard ,Ich benutze für die Datenbank Windows 11 und postgres ist ebenfalls in der Version 11 am Start. Die Datenbank habe ich dir als dump geschickt.Ich habe versucht den layer BP_ueberbaubare_Grundstuecksflaeche zu editieren.Gruß JeltoVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Bernhard Ströbl ***@***.***> Datum: 16.12.21  09:26  (GMT+01:00) An: bstroebl/xplanplugin ***@***.***> Cc: JeltoBuurman ***@***.***>, Author ***@***.***> Betreff: Re: [bstroebl/xplanplugin] Keine Texte und Nutzungsschablone (Issue #12) 

XPlanung nutz auch die DataDrivenInputMask, d.h. genau das selbe müsste dort auch nicht gehen. Mir wurde der Value out of range - Fehler bereits berichtet. Ich konnte ihn hier nicht reproduzieren. Welchen LAyer versuchst Du mit der DDIM zu bearbeiten? Auf welchem Betriebssystem läuft Deine DB?

**Comment by bstroebl** [comment]
Ich **vermute**, dass sich die DB unter Windows anders verhält, was die Größe von Integern angeht. Weiß Jürgen da vielleicht etwas? Könntest Du mir bitte die komplette Fehlermeldung schicken.

**Comment by JeltoBuurman** [comment]
Hallo Bernhard,

die Fehlermeldung ist:

Fehler bei der Ausführung folgenden Codes:
app=QgsApplication.instance();ddManager=app.xpManager;ddManager.showDdForm(16);


Traceback (most recent call last):
  File "", line 1, in
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddmanager.py",
line 522, in showDdForm
    self.showFeatureForm(aLayer,  feat)
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddmanager.py",
line 458, in showFeatureForm
    dlg = DdDialog(self, ui, layer, feature, db, multiEdit,
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\dddialog.py",
line 60, in __init__
    self.initialize()
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\dddialog.py",
line 81, in initialize
    self.ui.initialize(self.layer, self.feature, self.db, self.mode)
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddui.py",
line 1213, in initialize
    aForm.initialize(layer, feature, db, mode)
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddui.py",
line 1441, in initialize
    anInputWidget.initialize(self.layer, self.feature, db, self.mode)
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddui.py",
line 1872, in initialize
    self.setValidator(min = thisValue,  max = thisValue)
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddui.py",
line 2335, in setValidator
    validator = ddtools.getIntValidator(self.inputWidget,
self.attribute, min, max)
  File "C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddtools.py",
line 113, in getIntValidator
    validator.setBottom(thisMin)
OverflowError: argument 1 overflowed: value must be in the range
-2147483648 to 2147483647

Python-Version:
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit
(AMD64)]

QGIS-Version:
3.22.1-Białowieża 'Białowieża', 663dcf8fb9

Python-Pfad:
['C:\\Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\open_lidar_tools',
'C:\\Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\LAStools',
'C:/OSGeo4W/apps/qgis/./python',
'C:/Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python',
'C:/Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins',
'C:/OSGeo4W/apps/qgis/./python/plugins', 'C:\\OSGeo4W\\bin\\python39.zip',
'C:\\OSGeo4W\\apps\\Python39\\DLLs', 'C:\\OSGeo4W\\apps\\Python39\\lib',
'C:\\OSGeo4W\\bin', 'C:\\OSGeo4W\\apps\\Python39',
'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages',
'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\GDAL-3.4.0-py3.9-win-amd64.egg',
'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\win32',
'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\win32\\lib',
'C:\\OSGeo4W\\apps\\Python39\\lib\\site-packages\\Pythonwin',
'C:/Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python',
'C:\\Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\DataDrivenInputMask',
'C:\\Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\qgis_resource_sharing',
'C:\\Users\\jelto\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qgis_resource_sharing',
'C:\\Users\\jelto\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qgis_resource_sharing\\ext_libs',
'C:\\Users/jelto/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\rvt-qgis',
'C:/Users/jelto/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/DataDrivenInputMask']


Ich habe das Probelm auch an Jürgen weitergeleitet.


Gruß


Jelto

Am Do., 16. Dez. 2021 um 11:09 Uhr schrieb Bernhard Ströbl <
***@***.***>:

**Comment by JeltoBuurman** [comment]
Hallo Bernhard,

mit dieser Datei von Jürgen bekomme ich den Fehler nicht mehr.

Gruß
Jelto

---------- Forwarded message ---------
Von: Jürgen E. Fischer ***@***.***>
Date: Do., 16. Dez. 2021 um 18:41 Uhr
Subject: Re: Fwd: [bstroebl/xplanplugin] Keine Texte und Nutzungsschablone
(Issue #12)
To: Jelto Buurman ***@***.***>


Moin Jelto,

On Thu, 16. Dec 2021 at 17:25:02 +0100, Jelto Buurman wrote:
>   File
"C:\Users/jelto/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataDrivenInputMask\ddtools.py",
> line 113, in getIntValidator
>     validator.setBottom(thisMin)
> OverflowError: argument 1 overflowed: value must be in the range
> -2147483648 to 2147483647

Probier's mal mit dem anlegten ddtools.py.


Jürgen

-- 
Jürgen E. Fischer         norBIT GmbH               Tel. +49-4931-918175-31
Dipl.-Inf. (FH)           Rheinstraße 13            Fax. +49-4931-918175-50
Software Engineer         D-26506 Norden              https://www.norbit.de

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.9 (GNU/Linux)

iQIVAwUAYbt6RBBsJ9SQbsVUAQjKiQ//W/OQio6LQDXut08svKnzwym+2rujUAy7
iw2bNRJI86kR+KGVz8OBC04mahoBT9T5E3daFEEd9NeXnVecPeNaB3UCWzS23385
0Nqw9UiXtsGLp20g9y0y8KbBu5W8QqqK6fYtV8Eon+VHt+11XJzoHHVlhidicezx
yuETjwhJAlO/85REGuNQ2eTDyU5xq60W+gQM4jMSNjk7HTT6BAKcZGKMeutnnZFf
xJFcPUxPqZlb65WnaqiZVr95u1xlKur4ICq1k6io8HC6wMrSCoXyqjepWsIE9aqV
JC2VOPNiFCP14yPMrLN/pfXLLaRVRkgUCOhd5me1965IuWD3XkNeGzBu5U2b4Sx1
dIGVLb1RM3p7Pj/Q0A1nibRu1X8pyMtd46W7ACjqtzk6oAnyXQfZkTwoTKd7bQKa
L3m8JX1flYppWHajefHbKmpVlf9yf6ZJZqUOhqhZPrFWDRi5V8SwfemahxNVkxak
riP8fzncHHT/hKMQoO4JmjGE1icRNihsz3LfwTV5MwXAimmMVmNhdEliaOfGWYaG
3HDXLBP4zSX9zwJhBcldGXJpjswGP7tpThNh3648aDVyAX/goBjfqJlKYv7VI1us
2ithtfxvCM+SHL4et6D0yhI5CErp2wEUIqE+YMPe+IybTuXLnCXxHzc8EWJZ8ueZ
Wx++VlncmeA=
=xn2F
-----END PGP SIGNATURE-----

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/
