### ISSUE TITLE
Import schlägt fehl, wenn <xplan:aendert>-Node enthalten ist

### ISSUE THREAD

**Issue by swen100** [bstroebl/xplanplugin#8]
Hallo Herr Ströbl,

bei einem Test-Import eines Plans mit einer FNP-Änderung ist der Import in QGIS mit der Fehlermeldung

*"XPlanung: Mehrere Planobjektklassen im Importschema test oder mehrere Importschemas gefunden! Es kann immer nur eine Klasse aus einem Schema importiert werden"*

fehlgeschlagen.
Das GML habe ich durch diverse Validatoren prüfen lassen. Alles i.O.

Ich habe dann versucht herauszufinden, woran das liegen könnte und den Inhalt der GML-Datei schrittweise reduziert. Nach dem Entfernen des folgenden Inhalts:

```xml
<xplan:aendert>
        <xplan:XP_VerbundenerPlan>
          <xplan:planName>Flächennutzugsplan der Gemeinde Rieseby</xplan:planName>
          <xplan:rechtscharakter>1000</xplan:rechtscharakter>
        </xplan:XP_VerbundenerPlan>
      </xplan:aendert>
```

ist der Import erfolgreich durchgelaufen.

Hier ist die Original-Datei, damit Sie das Verhalten reproduzieren können:
[12Ae_FNP_Rieseby_5_1.zip](https://github.com/bstroebl/xplanplugin/files/4632929/12Ae_FNP_Rieseby_5_1.zip)

Grüße,
Swen Zanon

**Comment by bstroebl** [comment]
Hallo Herr Zanon,
der Fehler sollte mit dem master des Plugins nicht mehr auftreten, wurde in bc49098fa44b98dd35a17152c016bf045c200412 gefixt.
Bitte testen Sie damit und schließen Sie dieses Ticket, wenn der Test erfolgreich verlief.

**Comment by swen100** [comment]
OK, geht unter QGIS 3.x
